groupName: acme.loupeznik.dev

image:
  repository: ghcr.io/loupeznik/cert-manager-webhook-better-wapi
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
