apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "better-wapi-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "better-wapi-webhook.name" . }}
    chart: {{ include "better-wapi-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "better-wapi-webhook.fullname" . }}:secret-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "better-wapi-webhook.name" . }}
    chart: {{ include "better-wapi-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "better-wapi-webhook.fullname" . }}:secret-reader
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "better-wapi-webhook.name" . }}
    chart: {{ include "better-wapi-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "better-wapi-webhook.fullname" . }}:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "better-wapi-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "better-wapi-webhook.fullname" . }}:flowcontrol-solver
  labels:
    app: {{ include "better-wapi-webhook.name" . }}
    chart: {{ include "better-wapi-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - prioritylevelconfigurations
      - flowschemas
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "better-wapi-webhook.fullname" . }}:flowcontrol-solver
  labels:
    app: {{ include "better-wapi-webhook.name" . }}
    chart: {{ include "better-wapi-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "better-wapi-webhook.fullname" . }}:flowcontrol-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "better-wapi-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
